# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'test-pool'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'acrpositest'
    repository: 'nginx-echo-headers'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: 'latest'
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Posicube_Azure Subscription_Web Direct(a395aa84-0fb6-4a28-99c6-0a629fc13036)'
    azureResourceGroup: 'posicube-test-rg'
    kubernetesCluster: 'posicube-test-cluster'
    useClusterAdmin: true
    namespace: 'test'
    command: 'apply'
    arguments: '-f deploy.yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'